name: build2

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "mkdocs.yaml"
      - ".readthedocs.yaml"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "mkdocs.yaml"
      - ".readthedocs.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.3'

      - name: install dependencies
        run: |
          sudo apt install -y make automake bison

      - name: set gcc
        run: |
          export CFLAGS="-Wno-error"
          export CXXFLAGS="-Wno-error"
          echo $CFLAGS
          echo $CXXFLAGS

      - name: Checkout code
        uses: actions/checkout@v2

      - name: build
        run: |
          ls -l
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=OFF -DWITH_MKL=ON -DWITH_MKLDNN=OFF -DWITH_GPU=OFF -DWITH_FLUID_ONLY=ON ..
          make -j16 -i CFLAGS="... -Wno-error" CXXFLAGS="... -Wno-error"
